web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./:/www
        - ./serverconfig/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php-fpm
    environment:
        - TYPO3_CONTEXT=Development/alexgunkel
php-fpm:
    build: ./serverconfig/php/fpm
    links:
        - mariadb:mariadb
    volumes:
        - ./:/www
    environment:
        - TYPO3_CONTEXT=${TYPO3_CONTEXT}
php-cli:
    build: ./serverconfig/php/cli
    links:
        - mariadb:mariadb
    volumes:
        - ./:/www
    environment:
        - TYPO3_CONTEXT=${TYPO3_CONTEXT}
mariadb:
    image: mariadb:latest
    ports:
        - 3301:3306
    volumes:
        - ./serverconfig/mariadb/dbDataVolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${mariaDbRootPassword}
      - MYSQL_USER=${mariaDbUser}
      - MYSQL_PASSWORD=${mariaDbPassword}
      - MYSQL_DATABASE=${mariaDb}
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
       - mariadb:db
    ports:
     - 8080:80
    volumes:
     - /sessions
