web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./:/www
        - ./serverconfig/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
    environment:
        - TYPO3_CONTEXT=Development/alexgunkel
php:
    build: ./serverconfig/php
    links:
        - mariadb:mariadb
    volumes:
        - ./:/www
    environment:
        - TYPO3_CONTEXT=Development/AG
mariadb:
    image: mariadb:5.5
    ports:
        - 3301:3306
    volumes:
        - ./serverconfig/mariadb/dbDataVolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=user
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
       - mariadb:db
    ports:
     - 8080:80
    volumes:
     - /sessions
